// Generated by scripts/generate-contract.ts from api/openapi.yaml. Do not edit.

export interface LoginRequest {
  username: string;
  password: string;
}

export interface AuthSession {
  authenticated: boolean;
  insecureDevelopment: boolean;
}

export interface ApiError {
  code: ErrorCode;
  message: string;
  correlationId: CorrelationId;
  operationId?: OperationId;
  retryable?: boolean;
}

export type ErrorCode = "authentication_required" | "bad_request" | "internal_error" | "confirmation_required" | "controller_required" | "controller_generation_mismatch" | "challenge_expired" | "connection_required" | "mutation_not_allowed" | "operation_id_limit_reached" | "operation_result_unavailable" | "origin_rejected" | "request_too_large" | "safety_generation_mismatch" | "watchlist_limit_reached" | "browse_budget_exhausted";

export interface BuildInfo {
  buildVersion: string;
}

export interface HealthStatus {
  status: "ok" | "ready";
}

export interface Snapshot {
  sequence: number;
  buildVersion: string;
  generatedAt: string;
  controller: ControllerState;
  safety: SafetyState;
  connection: ConnectionSummary;
  selectedNodeId?: string;
  nodes: AddressSpaceNode[];
}

export interface ControllerState {
  role: "controller" | "observer";
  controllerGeneration: number;
  leaseExpiresAt?: string;
}

export interface SafetyState {
  readOnly: boolean;
  safetyGeneration: number;
  reason?: string;
}

export interface ConnectionSummary {
  state: "disconnected" | "connecting" | "connected" | "recovering" | "lost";
  endpoint?: string;
  securityPolicy?: string;
  securityMode?: "None" | "Sign" | "SignAndEncrypt";
  identityStatus?: "unverified" | "verified" | "replacementPending" | "notApplicable";
  serverCertificate?: ServerCertificateSummary;
  clientCertificate?: CertificateReference;
}

export interface ServerCertificateSummary {
  algorithm: "sha256";
  fingerprint: string;
}

export interface CertificateReference {
  displayName: string;
  reference: string;
}

export interface AddressSpaceNode {
  nodeId: string;
  nodeClass: "Object" | "Variable" | "Method" | "View" | "DataType" | "ReferenceType" | "ObjectType" | "VariableType";
  browseName: string;
  displayName: string;
  dataType?: string;
  access?: "read" | "readWrite" | "none";
  liveValue?: LiveValue;
}

export interface LiveValue {
  displayValue: string;
  status: string;
  sourceTimestamp?: string;
  serverTimestamp?: string;
  stale: boolean;
  outOfRange?: boolean;
}

export interface EventEnvelope {
  sequence: number;
  buildVersion: string;
  type: "snapshot-required" | "ownership-changed" | "safety-changed" | "connection-changed" | "live-value-changed";
  payload: SnapshotRequiredPayload | OwnershipChangedPayload | SafetyChangedPayload | ConnectionChangedPayload | LiveValueChangedPayload;
}

export interface SnapshotRequiredPayload {
  reason: "initial" | "reconnect" | "gap" | "version-mismatch" | "slow-client";
}

export interface OwnershipChangedPayload {
  role: "controller" | "observer";
  controllerGeneration: number;
}

export interface SafetyChangedPayload {
  readOnly: boolean;
  safetyGeneration: number;
  reason?: string;
}

export interface ConnectionChangedPayload {
  state: "disconnected" | "connecting" | "connected" | "recovering" | "lost";
  identityStatus?: "unverified" | "verified" | "replacementPending" | "notApplicable";
}

export interface LiveValueChangedPayload {
  nodeId: string;
  liveValue: LiveValue;
}

export type DiagnosticReport = DiagnosticRecord[];

export interface DiagnosticRecord {
  actor: string;
  endpoint: string;
  controllerGeneration: number;
  nodeId?: string;
  operationId: OperationId;
  correlationId: CorrelationId;
  outcome: "succeeded" | "rejected" | "unknown";
}

export type OperationId = string;

export type CorrelationId = string;

export type MutationKind = "variable-write" | "method-call";

export interface PrepareMutationRequest {
  operationId: OperationId;
  kind: MutationKind;
  targetNodeId: string;
  inputDigest: string;
}

export interface PrepareMutationResponse {
  challenge: MutationChallenge;
}

export interface MutationChallenge {
  operationId: OperationId;
  challenge: string;
  expiresAt: string;
  controllerGeneration: number;
  connectionGeneration: number;
  safetyGeneration: number;
  kind?: MutationKind;
  targetNodeId?: string;
}

export interface ConfirmMutationRequest {
  challenge: string;
}

export interface OperationOutcome {
  operationId: OperationId;
  correlationId: CorrelationId;
  status: "succeeded" | "rejected" | "unknown" | "retained";
  code?: ErrorCode;
  completedAt?: string;
}

export const loginRequestSchema = {"type":"object","additionalProperties":false,"required":["username","password"],"properties":{"username":{"type":"string","minLength":1,"maxLength":64},"password":{"type":"string","minLength":1,"maxLength":1024}}} as const;

export interface ContractResponse {
  ok: boolean;
  status: number;
  json(): Promise<unknown>;
}

export interface ContractRequestInit {
  method?: string;
  credentials?: "same-origin";
  headers?: Record<string, string>;
  body?: string;
}

export type ContractTransport = (input: string, init?: ContractRequestInit) => Promise<ContractResponse>;

export class ApiClientError extends Error {
  public constructor(public readonly status: number, public readonly error?: ApiError) {
    super(error?.message ?? "The request could not be completed.");
    this.name = "ApiClientError";
  }
}

const defaultTransport: ContractTransport = (input, init) => {
  const transport = (globalThis as { fetch?: ContractTransport }).fetch;
  if (!transport) throw new Error("A browser fetch implementation is required.");
  return transport(input, init);
};

export interface ApiClient {
  getLiveness(): Promise<HealthStatus>;
  getReadiness(): Promise<HealthStatus>;
  loginAdmin(request: LoginRequest): Promise<void>;
  logoutAdmin(): Promise<void>;
  getAuthenticationSession(): Promise<AuthSession>;
  getBuildInfo(): Promise<BuildInfo>;
  getSnapshot(): Promise<Snapshot>;
  attachEvents(afterSequence?: number): Promise<void>;
  getDiagnosticReport(): Promise<DiagnosticReport>;
  attachController(): Promise<ControllerState>;
  takeOverController(): Promise<ControllerState>;
  renewControllerLease(): Promise<void>;
  prepareMutation(request: PrepareMutationRequest): Promise<PrepareMutationResponse>;
  confirmMutation(operationId: OperationId, request: ConfirmMutationRequest): Promise<OperationOutcome>;
}

export function createApiClient(transport: ContractTransport = defaultTransport, baseUrl = ""): ApiClient {
  async function send<T>(method: string, route: string, body?: string): Promise<T> {
    const response = await transport(baseUrl + route, {
      method,
      credentials: "same-origin",
      ...(body === undefined ? {} : { headers: { "content-type": "application/json" }, body }),
    });
    if (!response.ok) {
      let error: ApiError | undefined;
      try {
        const payload = await response.json();
        if (isApiError(payload)) error = payload;
      } catch {
        // Keep transport failures generic and secret-free.
      }
      throw new ApiClientError(response.status, error);
    }
    if (response.status === 204) return undefined as T;
    return await response.json() as T;
  }

  return {
  getLiveness(): Promise<HealthStatus> {
    return send<HealthStatus>("GET", "/health/live");
  },

  getReadiness(): Promise<HealthStatus> {
    return send<HealthStatus>("GET", "/health/ready");
  },

  loginAdmin(request: LoginRequest): Promise<void> {
    return send<void>("POST", "/api/v1/auth/login", JSON.stringify(request));
  },

  logoutAdmin(): Promise<void> {
    return send<void>("POST", "/api/v1/auth/logout");
  },

  getAuthenticationSession(): Promise<AuthSession> {
    return send<AuthSession>("GET", "/api/v1/auth/session");
  },

  getBuildInfo(): Promise<BuildInfo> {
    return send<BuildInfo>("GET", "/api/v1/build");
  },

  getSnapshot(): Promise<Snapshot> {
    return send<Snapshot>("GET", "/api/v1/snapshot");
  },

  attachEvents(afterSequence?: number): Promise<void> {
    const query = new URLSearchParams();
    if (afterSequence !== undefined) query.set("afterSequence", String(afterSequence));
    const route = "/api/v1/events" + (query.toString() ? "?" + query.toString() : "");
    return send<void>("GET", route);
  },

  getDiagnosticReport(): Promise<DiagnosticReport> {
    return send<DiagnosticReport>("GET", "/api/v1/diagnostics");
  },

  attachController(): Promise<ControllerState> {
    return send<ControllerState>("POST", "/api/v1/controller/attach");
  },

  takeOverController(): Promise<ControllerState> {
    return send<ControllerState>("POST", "/api/v1/controller/takeover");
  },

  renewControllerLease(): Promise<void> {
    return send<void>("POST", "/api/v1/controller/renew");
  },

  prepareMutation(request: PrepareMutationRequest): Promise<PrepareMutationResponse> {
    return send<PrepareMutationResponse>("POST", "/api/v1/mutations/prepare", JSON.stringify(request));
  },

  confirmMutation(operationId: OperationId, request: ConfirmMutationRequest): Promise<OperationOutcome> {
    return send<OperationOutcome>("POST", "/api/v1/mutations/{operationId}/confirm".replace("{operationId}", encodeURIComponent(String(operationId))), JSON.stringify(request));
  }
  };
}

function isApiError(value: unknown): value is ApiError {
  return typeof value === "object" && value !== null && typeof (value as { code?: unknown }).code === "string" && typeof (value as { message?: unknown }).message === "string" && typeof (value as { correlationId?: unknown }).correlationId === "string";
}
